spring.application.name=404-Found-Group-Assignment

# Default Profile
spring.profiles.active=dev

# JPA
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true